[project]
name = "oreilly-2025-06june-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "marimo>=0.13.15",
    "openai>=1.88.0",
    "python-lsp-server[all]>=1.12.2",
]
